[project]
name = "VizFun"
version = "0.1.0"
description = "Add a short description here"
authors = ["luizzapria <lpria@student.hult.edu>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
numpy = ">=1.26.4,<1.27"
pytest = ">=8.1.1,<8.2"
pandas = ">=2.2.1,<2.3"
matplotlib = ">=3.8.4,<3.9"
python = ">=3.12.2,<3.13"
jupyter = ">=1.0.0,<1.1"
scipy = ">=1.13.0,<1.14"
seaborn = ">=0.13.2,<0.14"
